WITH FATURAMENTO AS (

SELECT
    CAST(CAST(EV.DESCRICAO AS VARCHAR(255) CHARACTER SET WIN1252) AS VARCHAR(255) CHARACTER SET UTF8) AS EVENTO,
    EV.EVENTO AS COD_EVENTO,
    PE.NOTA,
    TR.FANTASIA AS TRANSPORTADORA,
    CAST(PE.DATA AS DATE) AS DATA_NOTA,
    PE.PRODUTO,
    PE.COD_OPERACAO,
    M.CONDICOES_PGTO,
    CAST(CAST(CP.DESCRICAO AS VARCHAR(255) CHARACTER SET WIN1252) AS VARCHAR(255) CHARACTER SET UTF8) AS COND_PAGAMENTO,
    SUM(PE.QUANTIDADE) AS QUANTIDADE_NOTA,
    SUM(PE.PRECO_APLICADO * PE.QUANTIDADE) AS VALOR_PRODUTO_NOTA,
    SUM(PE.IT_VALOR_FRETE) AS VALOR_FRETE,
    SUM(PE.IT_DESP_ACESSORIAS) AS DESP_ACESSORIAS,
    SUM(PE.V_ICMSS) AS ICMS_ST,
    SUM(PE.V_FCPST) AS FCTPST,
    SUM(PE.V_IPI) AS IPI,
    SUM(PE.IT_VALOR_DESCONTO) AS VALOR_DESCONTO,
    SUM(PE.DESC_SUFRAMA) AS DESCONTO_SUFRAMA,
    SUM(
    	PE.PRECO_APLICADO * PE.QUANTIDADE +
        PE.IT_VALOR_FRETE +
        PE.IT_DESP_ACESSORIAS +
        PE.V_ICMSS +
        PE.V_FCPST +
        PE.V_IPI +
        PE.IT_VALOR_DESCONTO -
        PE.DESC_SUFRAMA
    ) AS VALOR_NOTA
FROM PRODUTOS_EVENTOS PE
INNER JOIN NF 
    ON PE.NOTA = NF.NOTA
    AND PE.COD_OPERACAO = NF.COD_OPERACAO
    AND NF.TIPO_OPERACAO = 'S'
    AND NF.CANCELADA = 'F'
    AND NF.FILIAL = 1
INNER JOIN SAIDAS S 
    ON PE.COD_OPERACAO = S.SAIDA
INNER JOIN MOVIMENTO M
	ON PE.COD_OPERACAO = M.COD_OPERACAO    
LEFT JOIN TRANSPORTADORAS TR
	ON M.TRANSPORTADORA = TR.TRANSPORTADORA
LEFT JOIN CONDICOES_PGTO CP 
    ON M.CONDICOES_PGTO = CP.CONDICOES_PGTO
    AND M.CONDICOES_PGTO IS NOT NULL
    AND M.CONDICOES_PGTO NOT IN ('9', '51')
INNER JOIN EVENTOS EV 
    ON S.EVENTO = EV.EVENTO
    AND EV.EVENTO IN (
        313, 8, 307, 166, 147, 119, 154, 203, 1, 316, 207,
        316, 741, 14, 9, 104, 105, 118, 306,
        301, 308, 167, 305, 103, 306714288, 321, 322
    )
WHERE PE.DATA BETWEEN '2023-12-01' AND '2026-12-31'
--AND PE.NOTA = 96780
GROUP BY 
	EV.DESCRICAO, 
	PE.NOTA, 
	PE.DATA, 
	PE.COD_OPERACAO,
	PE.PRODUTO,
	TR.FANTASIA,
    EV.EVENTO,
    CP.DESCRICAO,
    M.CONDICOES_PGTO
),

PEDIDOS_CANCELADOS AS (
	
SELECT 
	P.PEDIDOV,
	P.PRODUTO,
	P.QUITA_ITEM,
	P.ITEM,
	CAST(P.DATA_QUITA AS DATE) AS DATA_CANCELAMENTO,
          (
            SELECT FIRST 1 
                   CAST(CAST(MC.MOTIVO AS VARCHAR(255) CHARACTER SET WIN1252) AS VARCHAR(255) CHARACTER SET UTF8)
            FROM MOTIVOS_CANC MC
            WHERE MC.ORIGEM = P.PEDIDOV
            ORDER BY MC.DATA DESC
        ) AS MOTIVO_CANCELAMENTO
FROM PRODUTO_PEDIDOV P
INNER JOIN PEDIDO_VENDA PV
ON P.PEDIDOV = PV.PEDIDOV
WHERE 1=1 
AND P.QUITA_ITEM = 'T'
AND PV.FILIAL = 1
AND (PV.VENDEDOR <> 453 OR PV.VENDEDOR IS NULL)
AND PV.DATA_EMISSAO BETWEEN '2025-01-01' AND '2026-12-31'
	
),

COD_SAIDA AS (

	SELECT
		DISTINCT
		PEDIDOV,
		SAIDA
	FROM PRODUTO_PEDIDOV
	WHERE SAIDA IS NOT NULL
),

VENDAS AS (

SELECT
	CAST(C.COD_CLIENTE AS INTEGER) || P.COD_PRODUTO AS CHAVE_CLIENTE_PRODUTO,
	PPV.PRODUTO,
	CS.SAIDA,
	CP.CONDICOES_PGTO,
	CAST(CAST(CP.DESCRICAO AS VARCHAR(255) CHARACTER SET WIN1252) AS VARCHAR(255) CHARACTER SET UTF8) AS COND_PAGAMENTO,
	CASE
	    WHEN PV.OBS_CLI_FAT LIKE '%NATURAL TECH%' OR PV.OBS_CLI_FAT LIKE '%NATURALTECH%' OR PV.OBS_CLI_FAT LIKE '%NATURAL TEC%' OR PV.OBS_CLI_FAT LIKE '%MATURALTECH%' OR PV.OBS_CLI_FAT LIKE '%Natural Tec%' OR PV.OBS_CLI_FAT LIKE '%natural tec%' OR PV.OBS_CLI_FAT LIKE '%NATURATECH%' OR PV.OBS_CLI_FAT LIKE '%naturaltech%' OR PV.OBS_CLI_FAT LIKE '%Natural tec%' OR PV.OBS_CLI_FAT LIKE '%naturaltech%'
        THEN 'NATURALTECH 2025'
	    ELSE 'PEDIDO PADRÃO'
	END AS PEDIDO_FEIRA,
	PV.COD_PEDIDOV AS COD_PEDIDO,
    CAST(PV.DATA_EMISSAO AS DATE) AS DATA_PEDIDO,
    CASE
	    WHEN PC.QUITA_ITEM = 'T' THEN 'CANCELADO'
    	ELSE 'VIGENTE'
    END AS STATUS_PEDIDO_PRELIMINAR,
    CASE 
	    WHEN PC.QUITA_ITEM = 'T' THEN 'CANCELADO'
        WHEN PV.APROVADO = 'F' THEN 'EM NEGOCIAÇÃO'
        ELSE 'APROVADO'
    END AS STATUS_APROVACAO,
    PC.DATA_CANCELAMENTO,
    PC.MOTIVO_CANCELAMENTO,
    C.COD_CLIENTE,
    C.UFIE AS ESTADO,
    CASE
	    WHEN PV.VENDEDOR IS NULL THEN '-2000000000'
        WHEN PV.VENDEDOR = '474' THEN '473'
	    ELSE PV.VENDEDOR
	END AS COD_VENDEDOR,
    CAST(CAST(PV.OBS_CLI_FAT AS VARCHAR(1000) CHARACTER SET WIN1252) AS VARCHAR(1000) CHARACTER SET UTF8) AS OBS_PEDIDO,
    P.COD_PRODUTO,
    CASE 
    	WHEN SUM(PPV.QUANTIDADE) = 0 THEN SUM(PPV.ENTREGUE)
    	ELSE SUM(PPV.QUANTIDADE)
    END AS QUANTIDADE_PEDIDO,
    CASE 
    WHEN SUM(PPV.QUANTIDADE) = 0 
        THEN SUM(PPV.ENTREGUE * PPV.PRECO) * (1 + COALESCE(PV.ACERTO, 0) / 100.0)
    ELSE 
        SUM(PPV.QUANTIDADE * PPV.PRECO) * (1 + COALESCE(PV.ACERTO, 0) / 100.0)
	END AS VALOR_PEDIDO,
    PV.ORIGEM_PEDIDO
FROM PEDIDO_VENDA PV
INNER JOIN PRODUTO_PEDIDOV PPV 
    ON PV.PEDIDOV = PPV.PEDIDOV 
    --AND PPV.EMBALADO IN('T','F')
INNER JOIN PRODUTOS P 
    ON PPV.PRODUTO = P.PRODUTO
INNER JOIN CLIENTES C 
    ON C.CLIENTE = PV.CLIENTE 
    AND C.PF_PJ = 'PJ'
    AND C.COD_CLIENTE NOT LIKE '%C%'
LEFT JOIN PEDIDOS_CANCELADOS PC
	ON PC.PEDIDOV = PPV.PEDIDOV
	AND PC.PRODUTO = PPV.PRODUTO
	AND PC.ITEM = PPV.ITEM
LEFT JOIN COD_SAIDA CS
	ON PPV.PEDIDOV = CS.PEDIDOV
INNER JOIN CONDICOES_PGTO CP 
    ON PV.CONDICOES_PGTO = CP.CONDICOES_PGTO
    --AND PV.CONDICOES_PGTO IS NOT NULL
WHERE PV.DATA_EMISSAO IS NOT NULL
AND PV.FILIAL = 1
AND (PV.VENDEDOR <> 453 OR PV.VENDEDOR IS NULL)
AND PV.CONDICOES_PGTO IS NOT NULL
AND PV.CONDICOES_PGTO NOT IN ('9', '51')
AND PV.TIPO_PEDIDO NOT IN ('20211')
AND PV.DATA_EMISSAO BETWEEN '2023-12-01' AND '2026-12-31'
AND NOT (PV.ORIGEM_PEDIDO = 'COPIADO' AND CAST(PV.DATA_EMISSAO AS DATE) = CAST('2025-10-21' AS DATE))
GROUP BY 
	PV.COD_PEDIDOV,	
	PV.OBS_CLI_FAT,
    PV.DATA_EMISSAO,
    PV.APROVADO,
    C.COD_CLIENTE,
    C.UFIE,
    PV.VENDEDOR,
    P.COD_PRODUTO,
    PC.QUITA_ITEM,
    PC.DATA_CANCELAMENTO,
    PC.MOTIVO_CANCELAMENTO,
    PPV.PRODUTO,
	CS.SAIDA,
	CP.CONDICOES_PGTO,
	CP.DESCRICAO,
	PV.ORIGEM_PEDIDO,
	COALESCE(PV.ACERTO, 0) --ALTEREI AQUI 
)

SELECT
	V.CHAVE_CLIENTE_PRODUTO,
	V.PEDIDO_FEIRA,
	V.COD_PEDIDO,
	V.DATA_PEDIDO,
	CASE
    	WHEN FT.COD_EVENTO IN (313, 8, 307, 166, 147, 119, 154, 203, 1, 316) OR FT.CONDICOES_PGTO IN ('8', '40596') THEN 'BONIFICAÇÃO'
    	WHEN V.CONDICOES_PGTO IN ('8', '40596') THEN 'BONIFICAÇÃO'
    	ELSE 'VENDA'
    END AS TIPO_PEDIDO, 
	CASE
		WHEN V.STATUS_PEDIDO_PRELIMINAR = 'CANCELADO' THEN 'CANCELADO'
		WHEN FT.NOTA IS NULL THEN 
			CASE 
				WHEN V.STATUS_PEDIDO_PRELIMINAR = 'VIGENTE' AND EXTRACT(YEAR FROM V.DATA_PEDIDO) <= 2024 THEN 'CANCELADO'
				ELSE 'ABERTO'
			END
		ELSE 'FATURADO'
	END AS STATUS_PEDIDO,
	V.STATUS_APROVACAO,
	V.DATA_CANCELAMENTO,
    V.MOTIVO_CANCELAMENTO,
    V.COD_CLIENTE,
    V.ESTADO,
	V.COD_VENDEDOR,
	V.OBS_PEDIDO,
	V.COD_PRODUTO,
	V.QUANTIDADE_PEDIDO,
	V.VALOR_PEDIDO,
	CASE
		WHEN FT.COND_PAGAMENTO IS NULL THEN V.COND_PAGAMENTO
		ELSE FT.COND_PAGAMENTO
	END AS COND_PGTO,
	FT.EVENTO,
    FT.NOTA,
    FT.TRANSPORTADORA,
    FT.DATA_NOTA,
    FT.QUANTIDADE_NOTA,
    FT.VALOR_PRODUTO_NOTA,
    FT.VALOR_FRETE,
    FT.DESP_ACESSORIAS,
    FT.ICMS_ST,
    FT.FCTPST,
    FT.IPI,
    FT.VALOR_DESCONTO,
    FT.DESCONTO_SUFRAMA,
    FT.VALOR_NOTA
FROM VENDAS V
LEFT JOIN FATURAMENTO FT
ON V.SAIDA = FT.COD_OPERACAO
AND V.PRODUTO = FT.PRODUTO
WHERE (FT.NOTA NOT IN (89236, 91873, 94163, 87158, 87169, 89782, 89448, 88390, 88702, 93918, 93392, 93345) OR FT.NOTA IS NULL)
--AND V.COD_PEDIDO = '187352'

UNION ALL

SELECT
	NULL AS CHAVE_CLIENTE_PRODUTO,
	'PEDIDO_PADRÃO' AS PEDIDO_FEIRA,
	NULL AS COD_PEDIDO,
	CAST(PE.DATA AS DATE) AS DATA_PEDIDO,
    CASE
    	WHEN CFOP.NAT_OPERACAO IN ('6.910', '5.910') THEN 'BONIFICAÇÃO'
    	ELSE 'VENDA'
    END AS TIPO_PEDIDO,
    'FATURADO' AS STATUS_PEDIDO,
    'APROVADO' AS STATUS_APROVACAO,
    NULL AS DATA_CANCELAMENTO,
    NULL AS MOTIVO_CANCELAMENTO,
    C.COD_CLIENTE, -- CODIGO DO CLIENTE DA NOTA
    NF.ESTADO, -- ESTADO DO CLIENTE
    CASE
	    WHEN M.FUNCIONARIO IS NULL THEN '-2000000000'
        WHEN M.FUNCIONARIO = '474' THEN '473'
	    ELSE M.FUNCIONARIO
	END AS COD_VENDEDOR,
	NULL AS OBS_PEDIDO,
    P.COD_PRODUTO, -- CODIGO DO PRODUTO (USADO PARA RETORNAR OS PRODUTOS EM NOTAS QUE NÃO TEM PEDIDO VINCULADO)
    NULL AS QUANTIDADE_PEDIDO, -- QUANTIDADE DO PRODUTO
    NULL AS VALOR_PEDIDO,
    CAST(CAST(CP.DESCRICAO AS VARCHAR(255) CHARACTER SET WIN1252) AS VARCHAR(255) CHARACTER SET UTF8) AS COND_PGTO, -- CONDIÇÃO DE PAGAMENTO
    CAST(CAST(EV.DESCRICAO AS VARCHAR(255) CHARACTER SET WIN1252) AS VARCHAR(255) CHARACTER SET UTF8) AS EVENTO, -- EVENTO DE SAÍDA DA NOTA     
    PE.NOTA, -- NUMERO DA NOTA
    TR.FANTASIA AS TRANSPORTADORA, -- NOME DA TRANPORTADORA 
    CAST(PE.DATA AS DATE) AS DATA_NOTA, -- DATA DE EMISSAO DA NOTA
    SUM(PE.QUANTIDADE) AS QUANTIDADE_NOTA, -- QUANTIDADE DO PRODUTO
    SUM(PE.PRECO_APLICADO * PE.QUANTIDADE) AS VALOR_PRODUTO_NOTA, -- VALOR DO PRODUTO
    SUM(PE.IT_VALOR_FRETE) AS VALOR_FRETE, -- VALOR DO FRETE
    SUM(PE.IT_DESP_ACESSORIAS) AS DESP_ACESSORIAS, -- VALOR DAS DESPESAS ACESSÓRIAS (ISOPOR)
    SUM(PE.V_ICMSS) AS ICMS_ST, -- VALOR DO ICMS
    SUM(PE.V_FCPST) AS FCTPST, -- VALOR DO FCTP
    SUM(PE.V_IPI) AS IPI, -- VALRO DO IPI
    SUM(PE.IT_VALOR_DESCONTO) + SUM(PE.IT_VALOR_CORTESIA) AS VALOR_DESCONTO, -- VALOR DO DESCONTO
    SUM(PE.DESC_SUFRAMA) AS DESCONTO_SUFRAMA, -- VALOR DO DESCONTO DE REGIÃO SUFRAMA
    SUM(
    	PE.PRECO_APLICADO * PE.QUANTIDADE +
        PE.IT_VALOR_FRETE +
        PE.IT_DESP_ACESSORIAS +
        PE.V_ICMSS +
        PE.V_FCPST +
        PE.V_IPI +
        PE.IT_VALOR_DESCONTO - -- DESCONTO JÁ ESTÁ NEGATIVO NA TABELA DE ORIGEM
        PE.DESC_SUFRAMA +
        PE.IT_VALOR_CORTESIA
    ) AS VALOR_NOTA -- VALOR TOTAL DA NOTA
FROM PRODUTOS_EVENTOS PE -- TABELA QUE CONTEM DADOS DA NOTA EM NÍVEL DE PRODUTO
INNER JOIN NF -- TABELA QUE COMTÉM OS DADOS DA NOTA EM NÍVEL DE CABEÇALHO
    ON PE.NOTA = NF.NOTA 
    AND PE.COD_OPERACAO = NF.COD_OPERACAO
    AND PE.TIPO_OPERACAO = NF.TIPO_OPERACAO
    AND NF.TIPO_OPERACAO = 'S' -- TIPO DE OPERAÇÃO DE SAÍDA
    AND NF.CANCELADA = 'F' -- NOTAS QUE NÃO FORAM CANCELADAS
    AND NF.FILIAL IN (1) -- FILIAIS
INNER JOIN SAIDAS S -- TABELA COM DADOS COMPLEMENTARES DE NOTAS DE SAÍDA 
    ON PE.COD_OPERACAO = S.SAIDA
INNER JOIN MOVIMENTO M -- TABELA COM DADOS COMPLEMENTARES DE MOVIMENTAÇÃO DAS NOTAS
	ON PE.COD_OPERACAO = M.COD_OPERACAO    
	AND PE.TIPO_OPERACAO = M.TIPO_OPERACAO
	AND (M.FUNCIONARIO NOT IN ('453') OR M.FUNCIONARIO IS NULL)
	AND (M.CONDICOES_PGTO NOT IN ('9', '51') OR M.CONDICOES_PGTO IS NOT NULL)
LEFT JOIN TRANSPORTADORAS TR -- TABELA COM DADOS DAS TRANSPORTADORAS
	ON M.TRANSPORTADORA = TR.TRANSPORTADORA
LEFT JOIN CONDICOES_PGTO CP -- TABELA COM O DESCRITIVO DAS CONDIÇÕES DE PAGAMENTO
    ON M.CONDICOES_PGTO = CP.CONDICOES_PGTO
LEFT JOIN PRODUTOS P -- TABELA COM DADOS DE CADASTRO DE PRODUTOS
	ON PE.PRODUTO = P.PRODUTO
LEFT JOIN CLIENTES C -- TABELA COM DADOS DE CADASTRO DE CLIENTES
	ON M.CLIENTE = C.CLIENTE
LEFT JOIN CFOP -- TABELA COM DESCRITIVO DO CFOP
	ON PE.CFOP = CFOP.CFOP
LEFT JOIN FILIAIS F
	ON NF.FILIAL = F.FILIAL 
LEFT JOIN EVENTOS EV -- TABELA COM O DESCRITIVO DOS EVENTOS
    ON S.EVENTO = EV.EVENTO
WHERE PE.DATA BETWEEN '2024-01-01' AND '2026-12-31' -- INTERVALO DE DATAS CONSULTADO
    AND EV.EVENTO IN (313, 8, 307, 166, 147, 119, 154, 203, 1, 316, 207, 316, 741, 14, 9, 104, 105, 118, 306, 301, 308, 167, 305, 103, 306714288, 321, 322) -- ENVENTOS DE FATURAMENTO E BONIFICAÇÃO
    AND PE.NOTA NOT IN (89236, 91873, 94163, 87158, 87169, 89782, 89448, 88390, 88702, 93918, 93392, 93345, 3997682, 4194080) -- NOTAS QUE NÃO FORMA CONSIDERADAS NO ORÇAMENTO DE 2024 DO B2B
    AND PE.PEDIDO IS NULL
GROUP BY 
	EV.DESCRICAO, 
	PE.NOTA, 
	PE.DATA, 
	PE.COD_OPERACAO,
	PE.PRODUTO,
	TR.FANTASIA,
    EV.CODIGO,
    CP.DESCRICAO,
    M.CONDICOES_PGTO,
    P.COD_PRODUTO,
    C.COD_CLIENTE,
    NF.ESTADO,
    PE.PEDIDO,
    CFOP.NAT_OPERACAO,
    F.COD_FILIAL,
    M.FUNCIONARIO