
-- CONSULTA GERAL DE CLIENTES COM O RESUMO DE QUANTIDADE DE COMPRAS, COMPRAS EM ABERTO, QUANTAS PAGAS EM DIA E QUANTAS EM ATRASO
SELECT
    C.COD_CLIENTE,
    C.NOME,
    COUNT(*) AS TOTAL_COMPRAS,
    SUM(CASE WHEN L.EFETUADO = 'F' THEN 1 ELSE 0 END) AS EM_ABERTO,
    SUM(CASE WHEN L.EFETUADO = 'T' AND L.DATA_PAGAMENTO > L.DATA_VENCIMENTO THEN 1 ELSE 0 END) AS PAGAS_EM_ATRASO,
    SUM(CASE WHEN L.EFETUADO = 'T' AND L.DATA_PAGAMENTO <= L.DATA_VENCIMENTO THEN 1 ELSE 0 END) AS PAGAS_EM_DIA,
    CAST(
        SUM(CASE WHEN L.EFETUADO = 'T' AND L.DATA_PAGAMENTO > L.DATA_VENCIMENTO THEN 1 ELSE 0 END) AS DOUBLE PRECISION
    ) / NULLIF(SUM(CASE WHEN L.EFETUADO = 'T' THEN 1 ELSE 0 END), 0) AS PERCENTUAL_ATRASO
FROM LANCAMENTOS L
INNER JOIN CLIENTES C ON L.COD = C.CLIENTE
WHERE L.TIPO = 'R'
  AND L.GERADOR = 'C'
  AND L.FILIAL = 1
  AND C.COD_CLIENTE NOT LIKE '%C%'
  AND (L.DATA_PAGAMENTO IS NULL OR L.DATA_PAGAMENTO BETWEEN CAST('2019-01-01' AS DATE) AND CAST('TODAY' AS DATE) + 1)
GROUP BY C.COD_CLIENTE, C.NOME
HAVING COUNT(*) >= 3
ORDER BY PAGAS_EM_ATRASO DESC;




SELECT
    C.COD_CLIENTE,
    C.NOME,
    COUNT(*) AS TOTAL_COMPRAS,
    SUM(CASE WHEN L.EFETUADO = 'F' THEN 1 ELSE 0 END) AS EM_ABERTO,
    SUM(CASE WHEN L.EFETUADO = 'T' AND L.DATA_PAGAMENTO > L.DATA_VENCIMENTO THEN 1 ELSE 0 END) AS PAGAS_EM_ATRASO,
    SUM(CASE WHEN L.EFETUADO = 'T' AND L.DATA_PAGAMENTO <= L.DATA_VENCIMENTO THEN 1 ELSE 0 END) AS PAGAS_EM_DIA,
    CAST(
        SUM(CASE WHEN L.EFETUADO = 'T' AND L.DATA_PAGAMENTO > L.DATA_VENCIMENTO THEN 1 ELSE 0 END) AS DOUBLE PRECISION
    ) / NULLIF(SUM(CASE WHEN L.EFETUADO = 'T' THEN 1 ELSE 0 END), 0) AS PERCENTUAL_ATRASO
FROM LANCAMENTOS L
INNER JOIN CLIENTES C ON L.COD = C.CLIENTE
WHERE L.TIPO = 'R'
  AND L.GERADOR = 'C'
  AND L.FILIAL = 1
  AND C.COD_CLIENTE NOT LIKE '%C%'
  AND (
        L.N_DOCUMENTO SIMILAR TO '[0-9]+(/[A-Z0-9]+)?'
     OR L.N_DOCUMENTO LIKE 'SIA%'
      )
  AND (L.DATA_PAGAMENTO IS NULL OR L.DATA_PAGAMENTO BETWEEN CAST('2019-01-01' AS DATE) AND CAST('TODAY' AS DATE) + 1)
GROUP BY C.COD_CLIENTE, C.NOME
HAVING COUNT(*) >= 3
ORDER BY PAGAS_EM_ATRASO DESC;

